name: Java CI with Maven - Test and package
on: [pull_requests]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name : Package
        run : mvn -B package


